# Generated by Django 4.2.1 on 2023-07-06 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripcion')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Condicionado')], default='1', max_length=2, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=40, verbose_name='cantidad')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('detalle_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.detallecompra', verbose_name='Detalle compra')),
            ],
            options={
                'verbose_name_plural': 'stocks',
            },
        ),
    ]
