# Generated by Django 4.2.1 on 2023-07-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=45, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=60, verbose_name='Descripcion')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Condicionado')], default='1', max_length=2, verbose_name='Estado')),
            ],
        ),
    ]
