# Generated by Django 4.2.1 on 2023-08-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=45, verbose_name='Correo:')),
                ('usuario', models.CharField(max_length=45, verbose_name='Usuario:')),
                ('contraseña', models.CharField(max_length=45, verbose_name='Contraseña:')),
                ('activo', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Registers',
            },
        ),
    ]
