# Generated by Django 4.2.1 on 2023-08-19 23:58

from django.db import migrations, models
import django.db.models.deletion
import usuario.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_nombre', models.CharField(max_length=45, validators=[usuario.models.letras_validator], verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(max_length=45, validators=[usuario.models.letras_validator], verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(max_length=45, validators=[usuario.models.letras_validator], verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(max_length=45, validators=[usuario.models.letras_validator], verbose_name='Segundo Apellido')),
                ('tipo_documento', models.CharField(choices=[('CC', 'Cédula Ciudadania'), ('TI', 'Tarjeta de Identidad'), ('CE', 'Cédula de Extranjería')], max_length=2, verbose_name='Tipo de Documento')),
                ('documento', models.CharField(max_length=20, verbose_name='Documento')),
                ('telefono_contacto', models.CharField(max_length=10, verbose_name='Teléfono de contacto')),
                ('telefono_personal', models.CharField(max_length=10, verbose_name='Teléfono personal')),
                ('rol', models.CharField(choices=[('Empleado', 'Empleado'), ('Proveedor', 'Proveedor'), ('Cliente', 'Cliente')], max_length=10, verbose_name='Rol')),
                ('correo', models.CharField(max_length=40, verbose_name='Correo Electrónico')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo'), ('2', 'Condicionado')], default='1', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4')], max_length=1, verbose_name='Nivel de Salario')),
                ('fecha', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Salarios',
            },
        ),
    ]
