# Generated by Django 4.1.7 on 2023-05-29 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4')], max_length=1, verbose_name='Rol')),
                ('fecha', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name_plural': 'Roles',
            },
        ),
        migrations.AlterField(
            model_name='usuario',
            name='correo',
            field=models.CharField(max_length=40, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_contacto',
            field=models.CharField(max_length=10, verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_personal',
            field=models.CharField(max_length=10, verbose_name='Teléfono personal'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='tipo_documento',
            field=models.CharField(choices=[('CC', 'Cédula Ciudadania'), ('TI', 'Tarjeta de Idetidad'), ('CE', 'Cédula de Extranjería')], max_length=2, verbose_name='Tipo de Documento'),
        ),
        migrations.CreateModel(
            name='Usuario_Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.rol', verbose_name='Ficha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Usuario')),
            ],
        ),
    ]
