# Generated by Django 4.2.1 on 2023-08-20 15:32

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20, validators=[usuario.models.numeros_validator], verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_contacto',
            field=models.CharField(max_length=10, validators=[usuario.models.numeros_validator], verbose_name='Teléfono de contacto'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono_personal',
            field=models.CharField(max_length=10, validators=[usuario.models.numeros_validator], verbose_name='Teléfono personal'),
        ),
    ]
