# Generated by Django 4.2.1 on 2023-07-20 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_rol_alter_usuario_correo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario_Rol',
        ),
    ]
