# Generated by Django 4.2.1 on 2023-08-20 23:12

from django.db import migrations, models
import usuario.models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_documento_alter_usuario_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='documento',
            field=models.CharField(max_length=20, validators=[usuario.models.numeros_validator, usuario.models.unique_documento_validator], verbose_name='Documento'),
        ),
    ]
