# Generated by Django 4.2.1 on 2023-10-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_alter_usuario_documento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Empleado'),
        ),
    ]
