# Generated by Django 4.2.1 on 2023-07-20 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0003_delete_usuario_rol'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('1', 'Nivel 1'), ('2', 'Nivel 2'), ('3', 'Nivel 3'), ('4', 'Nivel 4')], max_length=1, verbose_name='Nivel de Salario')),
                ('fecha', models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha del Salario')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuario.usuario', verbose_name='Usuario')),
            ],
            options={
                'verbose_name_plural': 'Salarios',
            },
        ),
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
