# Generated by Django 4.2.1 on 2023-07-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_salario_delete_rol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salario',
            name='fecha',
            field=models.DateField(help_text='DD/MM/AAAA', verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('Empleado', 'Empleado'), ('Proveedor', 'Proveedor'), ('Cliente', 'Cliente')], max_length=10, verbose_name='Rol'),
        ),
    ]
