# Generated by Django 4.2.1 on 2023-07-31 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0005_alter_salario_fecha_alter_usuario_rol'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha')),
                ('numero_serie', models.CharField(max_length=100)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='usuario.usuario')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_recibidas', to='usuario.usuario')),
            ],
            options={
                'verbose_name_plural': 'compras',
            },
        ),
        migrations.CreateModel(
            name='Detallecompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.CharField(max_length=45, verbose_name='cantidad')),
                ('valortotal', models.CharField(max_length=45, verbose_name='valor total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compra.compra', verbose_name='Compra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Producto')),
            ],
            options={
                'verbose_name_plural': 'detallecompras',
            },
        ),
    ]
