# Generated by Django 4.1.7 on 2023-08-03 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0005_alter_salario_fecha_alter_usuario_rol'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='empleado_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_realizadas', to='usuario.usuario', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='compra',
            name='numero_serie',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='compra',
            name='proveedor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compras_recibidas', to='usuario.usuario', verbose_name='Proveedor'),
        ),
    ]
