# Generated by Django 4.2.1 on 2023-08-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallecompra',
            name='cantidad',
            field=models.IntegerField(max_length=45, verbose_name='cantidad'),
        ),
    ]
