# Generated by Django 4.2.1 on 2023-10-14 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0004_alter_salario_usuario'),
        ('compra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='aprendiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Proveedor', to='usuario.usuario', verbose_name='Proveedor'),
        ),
    ]
