# Generated by Django 4.2.1 on 2023-07-30 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuario', '0005_alter_salario_fecha_alter_usuario_rol'),
        ('producto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(max_length=100)),
                ('fecha', models.DateField(help_text='MM/DD/AAAA', verbose_name='Fecha')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('1', 'Activa'), ('0', 'Inactiva')], default='1', max_length=1, verbose_name='Estado')),
                ('cliente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_realizadas', to='usuario.usuario')),
                ('empleado_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas_atendidas', to='usuario.usuario')),
            ],
            options={
                'verbose_name_plural': 'ventas',
            },
        ),
        migrations.CreateModel(
            name='Detalleventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('valortotal', models.CharField(max_length=10, verbose_name='valor total')),
                ('estado', models.CharField(choices=[('1', 'Activo'), ('0', 'Inactivo')], default='1', max_length=1, verbose_name='Estado')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='producto.producto', verbose_name='Producto')),
                ('ventas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='venta.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name_plural': 'detalleventas',
            },
        ),
    ]
