# Generated by Django 4.1.7 on 2023-08-03 21:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_alter_venta_cliente_id_alter_venta_empleado_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='numero_serie',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=100, unique=True),
        ),
    ]
